In [1]:
import neural_net
import pandas as pd 
import pickle 
import numpy as np
import scipy.optimize as op
import time

In [2]:
from numpy import genfromtxt
train = genfromtxt('../../mnist_train.csv', delimiter=',')

In [5]:
y_inicial = np.expand_dims(train[:,0],1)
x_inicial = train[:,1:] / 1000
cat = 10
introduce_y = (y_inicial == np.arange(cat)).astype(int)

In [46]:
nodes_inicio = [500,500]
thetas = neural_net.forward_setup(nodes_inicio, x_inicial,introduce_y,len(nodes_inicio))
ingreso = neural_net.flatten_zetas(thetas)

In [47]:
comienzo = time.time()

resultado = op.minimize(
    fun=neural_net.cost,
    x0=ingreso[0],
    args=(ingreso[1],x_inicial,introduce_y),
    method='L-BFGS-B',
    jac=neural_net.backward_prop,
    options={
        'disp':True,
        'maxiter':1300
    }
)

guardar = open('./model.txt','wb')
pickle.dump(resultado.x,guardar)
guardar.close()

final = time.time()

In [48]:
print("executed in: ",(final - comienzo))

executed in:  236.108736038208


In [49]:
hola = resultado.x
resultado

      fun: nan
 hess_inv: <648010x648010 LbfgsInvHessProduct with dtype=float64>
      jac: array([0.     , 0.     , 0.     , ..., 0.90085, 0.90085, 0.90085])
  message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
     nfev: 21
      nit: 0
   status: 2
  success: False
        x: array([0.21235399, 0.12526667, 0.06002593, ..., 0.6988429 , 0.70954481,
       0.40243746])

In [50]:
# test 
model_thetas = neural_net.unflatten_zetas(hola,ingreso[1])

In [51]:
y_test = np.expand_dims(train[:,0],1)
x_test = train[:,1:] / 1000

In [52]:
respuestas = neural_net.forward_prop(x_test,model_thetas)

In [53]:
for i in respuestas[-1][:][:50]:
    print(i)

[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]
